title: "my name is kimbonobo"
tagline: "어서오세요."
description: "만나서 반갑습니다. ^^!"
github_username: tareqdandachi
baseurl: "/"
url: "https://kimbonobo.github.io"


plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  style: compressed

highlighter: rouge

header_pages:
  - index.md
  - read-me.md
  - preview.md

# set the size of the text to 'large' or 'small', default is small
font-size: small
